name: Build C++ (Linux)

on:
  push:
    branches: [ "main", "jdugan/add-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libwebsocketpp-dev libboost-all-dev
    - name: Build libSRDF
      working-directory: SpiderStream/_c++/libSpiderStream
      run: make && make install
    - name: Build ServerExample
      working-directory: SpiderStream/_c++/ServerExample
      run: make
